SET DEFINE OFF
SPOOL runme.log

SELECT USER || '@' || GLOBAL_NAME || ' ' || TO_CHAR (SYSDATE, 'DD.MM.YYYY HH24:MI:SS') "Script processed on"
       FROM GLOBAL_NAME
/

PROMPT ACC407P_TYPES_GRAF.sql
@@ACC407P_TYPES_GRAF.sql
SHOW ERRORS

PROMPT ACC407P_GRAF.sql
@@ACC407P_GRAF.sql
SHOW ERRORS

SPOOL OFF
